### ISSUE TITLE
NotAHero

### ISSUE THREAD

**Issue by Alexey-T** [Atbox/CodeChampion#3]
Not a Hero. Has 3 sounds for finishd level: 3 star, 4 star, 5 star. Most epic is 5 star. I like these :)

**Comment by saadeghi** [comment]
@Alexey-T I couldn't find the sounds. do you have any links?

**Comment by Alexey-T** [comment]
Like it - Not A Hero: Global Megalord Edition [L] [GOG] [ENG / ENG] (2015)
